apiVersion: batch/v1
kind: Job
metadata:
  name: sandbox-job
spec:
  template:
    spec:
      runtimeClassName: gvisor
      containers:
        - name: sandbox
          image: us-central1-docker.pkg.dev/intrepid-stage-489905-m7/gke-workflows/coding-agent:latest
          command: ["python3", "/app/sp26_gke/workflows/gke_agent_job.py"]
      restartPolicy: Never
