apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data:
  name: gke-cluster
contexts:
- context:
    cluster: gke-cluster
    user: gke-user
  name: gke-context
current-context: gke-context
users:
- name: gke-user
  user:
    token: ya29.a0ATkoCc40wn-GoTK9vq2aeew-tD-kGT8V9u2_wPB2gcBeCse79SI3G-jUk5T7jWvw8TTNQC_eYW3HKDJLVpz8_gDporHnIdMpeiyf-u95Wp7MuHYpb2ntzcq1m7nR2OlJJlKCBzwLHPBvgbQ5puwy7CTO4kDFLs2_OqpeRXRpwUVk0-IgPSd8B7FjLqhkwq3I76Ik04xJWviVtAaCgYKAQESARASFQHGX2MiL-2sz2GzL9Bq_8yGlez3Qg0213