apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data:
  name: gke-cluster
contexts:
- context:
    cluster: gke-cluster
    user: gke-user
  name: gke-context
current-context: gke-context
users:
- name: gke-user
  user:
    token: