apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRZWhSZFBhSVFVTFhJR2FNblNPWlUwekFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSaE5URXdNalZsWkMwek1HRXdMVFE0WVdFdE9XRmhOeTAwT1RZNE9EUmhOV1V5T1dNdwpJQmNOTWpZd016QTVNVFl5TnpRM1doZ1BNakExTmpBek1ERXhOekkzTkRkYU1DOHhMVEFyQmdOVkJBTVRKR0UxCk1UQXlOV1ZrTFRNd1lUQXRORGhoWVMwNVlXRTNMVFE1TmpnNE5HRTFaVEk1WXpDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUxIYXUwS0ZMYmRBVnhHV3dBOVRQb0tmSU56dEFsUkMwS2FVd0REdgpEOUdFZHpTL2llb3A4eGlYaG5xQU1KMWFrYWhGUC85VDdNN0NObUZuUVdWYnRnRFk5ZDlhVWtPWktoQUZab0dUCm9aY1NnQUZEWkxZY0xNN3k5UzBMbmZLYkpCRnRSRk9ObDVWZ0toblVBQURBalUwaEpTeFU1eEtXanlJNU41MzMKT2l4ckFkd05EMGl5VE1wWldaajFjWW9mc1l6VTFDR2pZd2xqdFZmNTZTZmJIRnBObmRpS0lzNnFiSUhUcCtZZwp5MEJicDk3OUE2QXR0akdYeUZ5UVlPWnJPTllMRURxaVI2SjA5RDhVSEhCZG80amZZR21oWVZoRUJUMnVQYkxlCnpNMlNaYmNEd3lOTG8zTVlTaXhkZ0trdnlSR3dmbHBjSjNadDNDVE1pWFRZNmJDVWlrQ2c0Ym9LWVByYjNKMmIKb0R5K2VQTGY4aTF2QzFUc2kxNnJLMkQ1OE1nYkxWVzdnNU05cXhFVzExS3U2ek0zUnRzT25WdmQxYlBKSGNXLwpKdVV0dWNNUHp4bHo0T2pFVUEvU3Q3MzNtbmRxUDFBd3JQT3JIemdEVFFFV0pySVpWamVxanA3VVg1UjhCRGt0ClJPdHcyS0dqbmhhbTlDREtEb3hvZ1FOL2Z3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVzNWNEaURWcWhuUEpXWW5DbXJmSk5ZUXJvMGN3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFEaEQyRk5EVzVkS0dnYSsxVHBWclhZM1JBUndnbVBmYVIrNTJMTFNKYXhBCnQxUUw3cHZhNlpkK0I4ODdFckc2SmFzOHg4QW9PRHRDMHhmQVRONVJrczdIaWtIQnNxbGJKR3RiZk11NC9yZmwKQjlRR0RuQUcrUHJOYlEvTjlsTE1odTNHT3hPUGtDYUExbUJKS1ZrVHpIckdyS3VLTUp3OU8vSTZDUko0OVdJNgpqZC90MVEycXAwK0VBOHF6RDErYlczVWNqTWJIOWxsbXJlaGZOUGxYNGJVWEZJaFozUzhsYmNpdWI0djZNL29HCmZhV0NERkRCMUZ2WXlCVlF1dTEwZkM3S0hDdjVqSjRFRzJGZEhpdVFvL1FZMGxoZlBlU0VjeEJBdFJDWEp0T2oKeW1JRVNKVlRkUUk4TGYySFo0NWR5U0dDTTFqY3lndVBsc2Z3NitjRmIrbXpZcjFYRXgxVVJpL2J3NExCNWxYQwphak8ybnBiWkU5YmdlSXhVL2kvbkdkR2s1Y2ZuemNLeTU0b3k1QVBTdVEveFZTb2pPZGlyYnNDbkdDSDZ5cjFJCk0xSmVqSDVZUzZ4YWEzd3NOd3dYaE5MU2VFdTFvK1pnNGFvRzVaMVcxK0lIbDhlTVRnWk93SWZwZ2Rxb1QvckUKTFFxTmhrTmNVVHUwOGJBU0g5bE1wQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.61.121.122
  name: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
contexts:
- context:
    cluster: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
    user: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
  name: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
current-context: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
kind: Config
users:
- name: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: /opt/homebrew/share/google-cloud-sdk/bin/gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      interactiveMode: IfAvailable
      provideClusterInfo: true
