apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: "REDACTED"
    server: https://34.61.121.122
  name: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
contexts:
- context:
    cluster: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
    user: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
  name: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
current-context: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
kind: Config
users:
- name: gke_cogent-nimbus-489503-f6_us-central1_coding-agent
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: /opt/homebrew/share/google-cloud-sdk/bin/gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      interactiveMode: IfAvailable
      provideClusterInfo: true
